import './globals.css'
import { Inter, Geologica } from 'next/font/google'
import localFont from 'next/font/local'

// Font files can be colocated inside of `app`
const allrox = localFont({
  src: '../public/fonts/Allrox.ttf',
  display: 'swap',
  variable: '--font-allrox',
})
const geologica = Geologica({ subsets: ['latin'], variable: '--font-geologica', display:'swap' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-black '>
      <body className={`${allrox.variable} ${geologica.variable} font-geologica`}>{children}</body>
    </html>
  )
}
